### ISSUE TITLE
Trying to build on iOS device...linker error

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [keenresearch/kaldi-ios-poc#5]
Get the following error when trying to build on iOS 12.1.4 device. Any tips?

ld: warning: ignoring file /Users/jeffbonasso/DevCode/AmbiFi/sandbox/keenasr/keenasr-ios-poc/KeenASR.framework/KeenASR, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (armv7): /Users/jeffbonasso/DevCode/AmbiFi/sandbox/keenasr/keenasr-ios-poc/KeenASR.framework/KeenASR
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_KIOSDecodingGraph", referenced from:
      objc-class-ref in EduWordsDemoViewController.o
      objc-class-ref in MusicDemoViewController.o
      objc-class-ref in FileRecognitionDemoViewController.o
      objc-class-ref in ContactsDemoViewController.o
      objc-class-ref in EduReadingDemoViewController.o
      objc-class-ref in CommandAndControlViewController.o
  "_OBJC_CLASS_$_KIOSRecognizer", referenced from:
      objc-class-ref in ViewController.o
      objc-class-ref in EduWordsDemoViewController.o
      objc-class-ref in MusicDemoViewController.o
      objc-class-ref in FileRecognitionDemoViewController.o
      objc-class-ref in ContactsDemoViewController.o
      objc-class-ref in EduReadingDemoViewController.o
      objc-class-ref in CommandAndControlViewController.o
      ...
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ognjentodic** [comment]
@jeffbonasso-ambifi Most likely the project (more precisely, KeenASR framework) wasn't checked out properly (see README for details on git-lfs). If you do:
`ls -l KeenASR.framework/Versions/Current/KeenASR` you should see something like this:

`-rw-rw-r--  1 ogi  staff  176426456 Mar  8 11:42 KeenASR.framework/Versions/Current/KeenASR`

I think your file will be much smaller (a git-lfs text file that points to the binary on git-lfs).

You'll need to make sure git-lfs is installed and I believe `git checkout` will do after that. This would also happen if you downloaded the zip archive, as it doesn't include large objects stored in git-lfs (if that's what you did you may want to remove the whole project, make sure git-lfs is installed, and just do `git clone git@github.com:keenresearch/keenasr-ios-poc.git`

Alternatively, you can remove KeenASR.Framework directory, download it from http://keenresearch.com/keenasr-downloads/KeenASR-Framework.tar.gz and unpack in the project directory.

The reason the library is large is bcs of bitcode compilation. It doesn't affect the app size in any significant manner.

**Comment by ognjentodic** [comment]
Also note that the SDK only works on devices (not on simulator); if you build for simulator you will see a similar error but mentioning x86_64 architecture not being supported.

**Comment by ognjentodic** [comment]
This was due to the fact that the project wasn't fully checked out (git-lfs part).
